# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdc47e4f78ba9d7faf3aed2508a7287dd1681733c74d25d952a18b282f75fcbf13049aacd2b63ddf2658d07133766636d27ef3873bf4884533377b0abcd770c7

test:
  secret_key_base: 462d26e3332ce89d0baeb152b82335292958867c094c09a869014d1bafa262498235be0a8c06f6d8973a15eca2fc1d353a0f625dfb8370d12bf3b500463a4d71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
